
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SaleEventProduct` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SaleEventProduct
 * 
 */
export type SaleEventProductModel = runtime.Types.Result.DefaultSelection<Prisma.$SaleEventProductPayload>

export type AggregateSaleEventProduct = {
  _count: SaleEventProductCountAggregateOutputType | null
  _avg: SaleEventProductAvgAggregateOutputType | null
  _sum: SaleEventProductSumAggregateOutputType | null
  _min: SaleEventProductMinAggregateOutputType | null
  _max: SaleEventProductMaxAggregateOutputType | null
}

export type SaleEventProductAvgAggregateOutputType = {
  amount: number | null
}

export type SaleEventProductSumAggregateOutputType = {
  amount: number | null
}

export type SaleEventProductMinAggregateOutputType = {
  id: string | null
  amount: number | null
  saleEventId: string | null
  productId: string | null
}

export type SaleEventProductMaxAggregateOutputType = {
  id: string | null
  amount: number | null
  saleEventId: string | null
  productId: string | null
}

export type SaleEventProductCountAggregateOutputType = {
  id: number
  amount: number
  saleEventId: number
  productId: number
  _all: number
}


export type SaleEventProductAvgAggregateInputType = {
  amount?: true
}

export type SaleEventProductSumAggregateInputType = {
  amount?: true
}

export type SaleEventProductMinAggregateInputType = {
  id?: true
  amount?: true
  saleEventId?: true
  productId?: true
}

export type SaleEventProductMaxAggregateInputType = {
  id?: true
  amount?: true
  saleEventId?: true
  productId?: true
}

export type SaleEventProductCountAggregateInputType = {
  id?: true
  amount?: true
  saleEventId?: true
  productId?: true
  _all?: true
}

export type SaleEventProductAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SaleEventProduct to aggregate.
   */
  where?: Prisma.SaleEventProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SaleEventProducts to fetch.
   */
  orderBy?: Prisma.SaleEventProductOrderByWithRelationInput | Prisma.SaleEventProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SaleEventProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SaleEventProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SaleEventProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SaleEventProducts
  **/
  _count?: true | SaleEventProductCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SaleEventProductAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SaleEventProductSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SaleEventProductMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SaleEventProductMaxAggregateInputType
}

export type GetSaleEventProductAggregateType<T extends SaleEventProductAggregateArgs> = {
      [P in keyof T & keyof AggregateSaleEventProduct]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSaleEventProduct[P]>
    : Prisma.GetScalarType<T[P], AggregateSaleEventProduct[P]>
}




export type SaleEventProductGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SaleEventProductWhereInput
  orderBy?: Prisma.SaleEventProductOrderByWithAggregationInput | Prisma.SaleEventProductOrderByWithAggregationInput[]
  by: Prisma.SaleEventProductScalarFieldEnum[] | Prisma.SaleEventProductScalarFieldEnum
  having?: Prisma.SaleEventProductScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SaleEventProductCountAggregateInputType | true
  _avg?: SaleEventProductAvgAggregateInputType
  _sum?: SaleEventProductSumAggregateInputType
  _min?: SaleEventProductMinAggregateInputType
  _max?: SaleEventProductMaxAggregateInputType
}

export type SaleEventProductGroupByOutputType = {
  id: string
  amount: number
  saleEventId: string
  productId: string
  _count: SaleEventProductCountAggregateOutputType | null
  _avg: SaleEventProductAvgAggregateOutputType | null
  _sum: SaleEventProductSumAggregateOutputType | null
  _min: SaleEventProductMinAggregateOutputType | null
  _max: SaleEventProductMaxAggregateOutputType | null
}

type GetSaleEventProductGroupByPayload<T extends SaleEventProductGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SaleEventProductGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SaleEventProductGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SaleEventProductGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SaleEventProductGroupByOutputType[P]>
      }
    >
  >



export type SaleEventProductWhereInput = {
  AND?: Prisma.SaleEventProductWhereInput | Prisma.SaleEventProductWhereInput[]
  OR?: Prisma.SaleEventProductWhereInput[]
  NOT?: Prisma.SaleEventProductWhereInput | Prisma.SaleEventProductWhereInput[]
  id?: Prisma.StringFilter<"SaleEventProduct"> | string
  amount?: Prisma.IntFilter<"SaleEventProduct"> | number
  saleEventId?: Prisma.StringFilter<"SaleEventProduct"> | string
  productId?: Prisma.StringFilter<"SaleEventProduct"> | string
  saleEvent?: Prisma.XOR<Prisma.SaleEventScalarRelationFilter, Prisma.SaleEventWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type SaleEventProductOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  saleEventId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  saleEvent?: Prisma.SaleEventOrderByWithRelationInput
  product?: Prisma.ProductOrderByWithRelationInput
}

export type SaleEventProductWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SaleEventProductWhereInput | Prisma.SaleEventProductWhereInput[]
  OR?: Prisma.SaleEventProductWhereInput[]
  NOT?: Prisma.SaleEventProductWhereInput | Prisma.SaleEventProductWhereInput[]
  amount?: Prisma.IntFilter<"SaleEventProduct"> | number
  saleEventId?: Prisma.StringFilter<"SaleEventProduct"> | string
  productId?: Prisma.StringFilter<"SaleEventProduct"> | string
  saleEvent?: Prisma.XOR<Prisma.SaleEventScalarRelationFilter, Prisma.SaleEventWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type SaleEventProductOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  saleEventId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  _count?: Prisma.SaleEventProductCountOrderByAggregateInput
  _avg?: Prisma.SaleEventProductAvgOrderByAggregateInput
  _max?: Prisma.SaleEventProductMaxOrderByAggregateInput
  _min?: Prisma.SaleEventProductMinOrderByAggregateInput
  _sum?: Prisma.SaleEventProductSumOrderByAggregateInput
}

export type SaleEventProductScalarWhereWithAggregatesInput = {
  AND?: Prisma.SaleEventProductScalarWhereWithAggregatesInput | Prisma.SaleEventProductScalarWhereWithAggregatesInput[]
  OR?: Prisma.SaleEventProductScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SaleEventProductScalarWhereWithAggregatesInput | Prisma.SaleEventProductScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SaleEventProduct"> | string
  amount?: Prisma.IntWithAggregatesFilter<"SaleEventProduct"> | number
  saleEventId?: Prisma.StringWithAggregatesFilter<"SaleEventProduct"> | string
  productId?: Prisma.StringWithAggregatesFilter<"SaleEventProduct"> | string
}

export type SaleEventProductCreateInput = {
  id?: string
  amount: number
  saleEvent: Prisma.SaleEventCreateNestedOneWithoutSaleEventProductsInput
  product: Prisma.ProductCreateNestedOneWithoutSaleEventProductsInput
}

export type SaleEventProductUncheckedCreateInput = {
  id?: string
  amount: number
  saleEventId: string
  productId: string
}

export type SaleEventProductUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  saleEvent?: Prisma.SaleEventUpdateOneRequiredWithoutSaleEventProductsNestedInput
  product?: Prisma.ProductUpdateOneRequiredWithoutSaleEventProductsNestedInput
}

export type SaleEventProductUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  saleEventId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SaleEventProductCreateManyInput = {
  id?: string
  amount: number
  saleEventId: string
  productId: string
}

export type SaleEventProductUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SaleEventProductUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  saleEventId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SaleEventProductListRelationFilter = {
  every?: Prisma.SaleEventProductWhereInput
  some?: Prisma.SaleEventProductWhereInput
  none?: Prisma.SaleEventProductWhereInput
}

export type SaleEventProductOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SaleEventProductCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  saleEventId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
}

export type SaleEventProductAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type SaleEventProductMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  saleEventId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
}

export type SaleEventProductMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  saleEventId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
}

export type SaleEventProductSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type SaleEventProductCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.SaleEventProductCreateWithoutProductInput, Prisma.SaleEventProductUncheckedCreateWithoutProductInput> | Prisma.SaleEventProductCreateWithoutProductInput[] | Prisma.SaleEventProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SaleEventProductCreateOrConnectWithoutProductInput | Prisma.SaleEventProductCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.SaleEventProductCreateManyProductInputEnvelope
  connect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
}

export type SaleEventProductUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.SaleEventProductCreateWithoutProductInput, Prisma.SaleEventProductUncheckedCreateWithoutProductInput> | Prisma.SaleEventProductCreateWithoutProductInput[] | Prisma.SaleEventProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SaleEventProductCreateOrConnectWithoutProductInput | Prisma.SaleEventProductCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.SaleEventProductCreateManyProductInputEnvelope
  connect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
}

export type SaleEventProductUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.SaleEventProductCreateWithoutProductInput, Prisma.SaleEventProductUncheckedCreateWithoutProductInput> | Prisma.SaleEventProductCreateWithoutProductInput[] | Prisma.SaleEventProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SaleEventProductCreateOrConnectWithoutProductInput | Prisma.SaleEventProductCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.SaleEventProductUpsertWithWhereUniqueWithoutProductInput | Prisma.SaleEventProductUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.SaleEventProductCreateManyProductInputEnvelope
  set?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  disconnect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  delete?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  connect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  update?: Prisma.SaleEventProductUpdateWithWhereUniqueWithoutProductInput | Prisma.SaleEventProductUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.SaleEventProductUpdateManyWithWhereWithoutProductInput | Prisma.SaleEventProductUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.SaleEventProductScalarWhereInput | Prisma.SaleEventProductScalarWhereInput[]
}

export type SaleEventProductUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.SaleEventProductCreateWithoutProductInput, Prisma.SaleEventProductUncheckedCreateWithoutProductInput> | Prisma.SaleEventProductCreateWithoutProductInput[] | Prisma.SaleEventProductUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.SaleEventProductCreateOrConnectWithoutProductInput | Prisma.SaleEventProductCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.SaleEventProductUpsertWithWhereUniqueWithoutProductInput | Prisma.SaleEventProductUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.SaleEventProductCreateManyProductInputEnvelope
  set?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  disconnect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  delete?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  connect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  update?: Prisma.SaleEventProductUpdateWithWhereUniqueWithoutProductInput | Prisma.SaleEventProductUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.SaleEventProductUpdateManyWithWhereWithoutProductInput | Prisma.SaleEventProductUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.SaleEventProductScalarWhereInput | Prisma.SaleEventProductScalarWhereInput[]
}

export type SaleEventProductCreateNestedManyWithoutSaleEventInput = {
  create?: Prisma.XOR<Prisma.SaleEventProductCreateWithoutSaleEventInput, Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput> | Prisma.SaleEventProductCreateWithoutSaleEventInput[] | Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput[]
  connectOrCreate?: Prisma.SaleEventProductCreateOrConnectWithoutSaleEventInput | Prisma.SaleEventProductCreateOrConnectWithoutSaleEventInput[]
  createMany?: Prisma.SaleEventProductCreateManySaleEventInputEnvelope
  connect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
}

export type SaleEventProductUncheckedCreateNestedManyWithoutSaleEventInput = {
  create?: Prisma.XOR<Prisma.SaleEventProductCreateWithoutSaleEventInput, Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput> | Prisma.SaleEventProductCreateWithoutSaleEventInput[] | Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput[]
  connectOrCreate?: Prisma.SaleEventProductCreateOrConnectWithoutSaleEventInput | Prisma.SaleEventProductCreateOrConnectWithoutSaleEventInput[]
  createMany?: Prisma.SaleEventProductCreateManySaleEventInputEnvelope
  connect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
}

export type SaleEventProductUpdateManyWithoutSaleEventNestedInput = {
  create?: Prisma.XOR<Prisma.SaleEventProductCreateWithoutSaleEventInput, Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput> | Prisma.SaleEventProductCreateWithoutSaleEventInput[] | Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput[]
  connectOrCreate?: Prisma.SaleEventProductCreateOrConnectWithoutSaleEventInput | Prisma.SaleEventProductCreateOrConnectWithoutSaleEventInput[]
  upsert?: Prisma.SaleEventProductUpsertWithWhereUniqueWithoutSaleEventInput | Prisma.SaleEventProductUpsertWithWhereUniqueWithoutSaleEventInput[]
  createMany?: Prisma.SaleEventProductCreateManySaleEventInputEnvelope
  set?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  disconnect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  delete?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  connect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  update?: Prisma.SaleEventProductUpdateWithWhereUniqueWithoutSaleEventInput | Prisma.SaleEventProductUpdateWithWhereUniqueWithoutSaleEventInput[]
  updateMany?: Prisma.SaleEventProductUpdateManyWithWhereWithoutSaleEventInput | Prisma.SaleEventProductUpdateManyWithWhereWithoutSaleEventInput[]
  deleteMany?: Prisma.SaleEventProductScalarWhereInput | Prisma.SaleEventProductScalarWhereInput[]
}

export type SaleEventProductUncheckedUpdateManyWithoutSaleEventNestedInput = {
  create?: Prisma.XOR<Prisma.SaleEventProductCreateWithoutSaleEventInput, Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput> | Prisma.SaleEventProductCreateWithoutSaleEventInput[] | Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput[]
  connectOrCreate?: Prisma.SaleEventProductCreateOrConnectWithoutSaleEventInput | Prisma.SaleEventProductCreateOrConnectWithoutSaleEventInput[]
  upsert?: Prisma.SaleEventProductUpsertWithWhereUniqueWithoutSaleEventInput | Prisma.SaleEventProductUpsertWithWhereUniqueWithoutSaleEventInput[]
  createMany?: Prisma.SaleEventProductCreateManySaleEventInputEnvelope
  set?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  disconnect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  delete?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  connect?: Prisma.SaleEventProductWhereUniqueInput | Prisma.SaleEventProductWhereUniqueInput[]
  update?: Prisma.SaleEventProductUpdateWithWhereUniqueWithoutSaleEventInput | Prisma.SaleEventProductUpdateWithWhereUniqueWithoutSaleEventInput[]
  updateMany?: Prisma.SaleEventProductUpdateManyWithWhereWithoutSaleEventInput | Prisma.SaleEventProductUpdateManyWithWhereWithoutSaleEventInput[]
  deleteMany?: Prisma.SaleEventProductScalarWhereInput | Prisma.SaleEventProductScalarWhereInput[]
}

export type SaleEventProductCreateWithoutProductInput = {
  id?: string
  amount: number
  saleEvent: Prisma.SaleEventCreateNestedOneWithoutSaleEventProductsInput
}

export type SaleEventProductUncheckedCreateWithoutProductInput = {
  id?: string
  amount: number
  saleEventId: string
}

export type SaleEventProductCreateOrConnectWithoutProductInput = {
  where: Prisma.SaleEventProductWhereUniqueInput
  create: Prisma.XOR<Prisma.SaleEventProductCreateWithoutProductInput, Prisma.SaleEventProductUncheckedCreateWithoutProductInput>
}

export type SaleEventProductCreateManyProductInputEnvelope = {
  data: Prisma.SaleEventProductCreateManyProductInput | Prisma.SaleEventProductCreateManyProductInput[]
}

export type SaleEventProductUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.SaleEventProductWhereUniqueInput
  update: Prisma.XOR<Prisma.SaleEventProductUpdateWithoutProductInput, Prisma.SaleEventProductUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.SaleEventProductCreateWithoutProductInput, Prisma.SaleEventProductUncheckedCreateWithoutProductInput>
}

export type SaleEventProductUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.SaleEventProductWhereUniqueInput
  data: Prisma.XOR<Prisma.SaleEventProductUpdateWithoutProductInput, Prisma.SaleEventProductUncheckedUpdateWithoutProductInput>
}

export type SaleEventProductUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.SaleEventProductScalarWhereInput
  data: Prisma.XOR<Prisma.SaleEventProductUpdateManyMutationInput, Prisma.SaleEventProductUncheckedUpdateManyWithoutProductInput>
}

export type SaleEventProductScalarWhereInput = {
  AND?: Prisma.SaleEventProductScalarWhereInput | Prisma.SaleEventProductScalarWhereInput[]
  OR?: Prisma.SaleEventProductScalarWhereInput[]
  NOT?: Prisma.SaleEventProductScalarWhereInput | Prisma.SaleEventProductScalarWhereInput[]
  id?: Prisma.StringFilter<"SaleEventProduct"> | string
  amount?: Prisma.IntFilter<"SaleEventProduct"> | number
  saleEventId?: Prisma.StringFilter<"SaleEventProduct"> | string
  productId?: Prisma.StringFilter<"SaleEventProduct"> | string
}

export type SaleEventProductCreateWithoutSaleEventInput = {
  id?: string
  amount: number
  product: Prisma.ProductCreateNestedOneWithoutSaleEventProductsInput
}

export type SaleEventProductUncheckedCreateWithoutSaleEventInput = {
  id?: string
  amount: number
  productId: string
}

export type SaleEventProductCreateOrConnectWithoutSaleEventInput = {
  where: Prisma.SaleEventProductWhereUniqueInput
  create: Prisma.XOR<Prisma.SaleEventProductCreateWithoutSaleEventInput, Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput>
}

export type SaleEventProductCreateManySaleEventInputEnvelope = {
  data: Prisma.SaleEventProductCreateManySaleEventInput | Prisma.SaleEventProductCreateManySaleEventInput[]
}

export type SaleEventProductUpsertWithWhereUniqueWithoutSaleEventInput = {
  where: Prisma.SaleEventProductWhereUniqueInput
  update: Prisma.XOR<Prisma.SaleEventProductUpdateWithoutSaleEventInput, Prisma.SaleEventProductUncheckedUpdateWithoutSaleEventInput>
  create: Prisma.XOR<Prisma.SaleEventProductCreateWithoutSaleEventInput, Prisma.SaleEventProductUncheckedCreateWithoutSaleEventInput>
}

export type SaleEventProductUpdateWithWhereUniqueWithoutSaleEventInput = {
  where: Prisma.SaleEventProductWhereUniqueInput
  data: Prisma.XOR<Prisma.SaleEventProductUpdateWithoutSaleEventInput, Prisma.SaleEventProductUncheckedUpdateWithoutSaleEventInput>
}

export type SaleEventProductUpdateManyWithWhereWithoutSaleEventInput = {
  where: Prisma.SaleEventProductScalarWhereInput
  data: Prisma.XOR<Prisma.SaleEventProductUpdateManyMutationInput, Prisma.SaleEventProductUncheckedUpdateManyWithoutSaleEventInput>
}

export type SaleEventProductCreateManyProductInput = {
  id?: string
  amount: number
  saleEventId: string
}

export type SaleEventProductUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  saleEvent?: Prisma.SaleEventUpdateOneRequiredWithoutSaleEventProductsNestedInput
}

export type SaleEventProductUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  saleEventId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SaleEventProductUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  saleEventId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SaleEventProductCreateManySaleEventInput = {
  id?: string
  amount: number
  productId: string
}

export type SaleEventProductUpdateWithoutSaleEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  product?: Prisma.ProductUpdateOneRequiredWithoutSaleEventProductsNestedInput
}

export type SaleEventProductUncheckedUpdateWithoutSaleEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  productId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SaleEventProductUncheckedUpdateManyWithoutSaleEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  productId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SaleEventProductSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  saleEventId?: boolean
  productId?: boolean
  saleEvent?: boolean | Prisma.SaleEventDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["saleEventProduct"]>

export type SaleEventProductSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  saleEventId?: boolean
  productId?: boolean
  saleEvent?: boolean | Prisma.SaleEventDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["saleEventProduct"]>

export type SaleEventProductSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  saleEventId?: boolean
  productId?: boolean
  saleEvent?: boolean | Prisma.SaleEventDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["saleEventProduct"]>

export type SaleEventProductSelectScalar = {
  id?: boolean
  amount?: boolean
  saleEventId?: boolean
  productId?: boolean
}

export type SaleEventProductOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "amount" | "saleEventId" | "productId", ExtArgs["result"]["saleEventProduct"]>
export type SaleEventProductInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  saleEvent?: boolean | Prisma.SaleEventDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type SaleEventProductIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  saleEvent?: boolean | Prisma.SaleEventDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type SaleEventProductIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  saleEvent?: boolean | Prisma.SaleEventDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $SaleEventProductPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SaleEventProduct"
  objects: {
    saleEvent: Prisma.$SaleEventPayload<ExtArgs>
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    amount: number
    saleEventId: string
    productId: string
  }, ExtArgs["result"]["saleEventProduct"]>
  composites: {}
}

export type SaleEventProductGetPayload<S extends boolean | null | undefined | SaleEventProductDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload, S>

export type SaleEventProductCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SaleEventProductFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SaleEventProductCountAggregateInputType | true
  }

export interface SaleEventProductDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SaleEventProduct'], meta: { name: 'SaleEventProduct' } }
  /**
   * Find zero or one SaleEventProduct that matches the filter.
   * @param {SaleEventProductFindUniqueArgs} args - Arguments to find a SaleEventProduct
   * @example
   * // Get one SaleEventProduct
   * const saleEventProduct = await prisma.saleEventProduct.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SaleEventProductFindUniqueArgs>(args: Prisma.SelectSubset<T, SaleEventProductFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SaleEventProductClient<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SaleEventProduct that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SaleEventProductFindUniqueOrThrowArgs} args - Arguments to find a SaleEventProduct
   * @example
   * // Get one SaleEventProduct
   * const saleEventProduct = await prisma.saleEventProduct.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SaleEventProductFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SaleEventProductFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SaleEventProductClient<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SaleEventProduct that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventProductFindFirstArgs} args - Arguments to find a SaleEventProduct
   * @example
   * // Get one SaleEventProduct
   * const saleEventProduct = await prisma.saleEventProduct.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SaleEventProductFindFirstArgs>(args?: Prisma.SelectSubset<T, SaleEventProductFindFirstArgs<ExtArgs>>): Prisma.Prisma__SaleEventProductClient<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SaleEventProduct that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventProductFindFirstOrThrowArgs} args - Arguments to find a SaleEventProduct
   * @example
   * // Get one SaleEventProduct
   * const saleEventProduct = await prisma.saleEventProduct.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SaleEventProductFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SaleEventProductFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SaleEventProductClient<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SaleEventProducts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventProductFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SaleEventProducts
   * const saleEventProducts = await prisma.saleEventProduct.findMany()
   * 
   * // Get first 10 SaleEventProducts
   * const saleEventProducts = await prisma.saleEventProduct.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const saleEventProductWithIdOnly = await prisma.saleEventProduct.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SaleEventProductFindManyArgs>(args?: Prisma.SelectSubset<T, SaleEventProductFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SaleEventProduct.
   * @param {SaleEventProductCreateArgs} args - Arguments to create a SaleEventProduct.
   * @example
   * // Create one SaleEventProduct
   * const SaleEventProduct = await prisma.saleEventProduct.create({
   *   data: {
   *     // ... data to create a SaleEventProduct
   *   }
   * })
   * 
   */
  create<T extends SaleEventProductCreateArgs>(args: Prisma.SelectSubset<T, SaleEventProductCreateArgs<ExtArgs>>): Prisma.Prisma__SaleEventProductClient<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SaleEventProducts.
   * @param {SaleEventProductCreateManyArgs} args - Arguments to create many SaleEventProducts.
   * @example
   * // Create many SaleEventProducts
   * const saleEventProduct = await prisma.saleEventProduct.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SaleEventProductCreateManyArgs>(args?: Prisma.SelectSubset<T, SaleEventProductCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SaleEventProducts and returns the data saved in the database.
   * @param {SaleEventProductCreateManyAndReturnArgs} args - Arguments to create many SaleEventProducts.
   * @example
   * // Create many SaleEventProducts
   * const saleEventProduct = await prisma.saleEventProduct.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SaleEventProducts and only return the `id`
   * const saleEventProductWithIdOnly = await prisma.saleEventProduct.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SaleEventProductCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SaleEventProductCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SaleEventProduct.
   * @param {SaleEventProductDeleteArgs} args - Arguments to delete one SaleEventProduct.
   * @example
   * // Delete one SaleEventProduct
   * const SaleEventProduct = await prisma.saleEventProduct.delete({
   *   where: {
   *     // ... filter to delete one SaleEventProduct
   *   }
   * })
   * 
   */
  delete<T extends SaleEventProductDeleteArgs>(args: Prisma.SelectSubset<T, SaleEventProductDeleteArgs<ExtArgs>>): Prisma.Prisma__SaleEventProductClient<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SaleEventProduct.
   * @param {SaleEventProductUpdateArgs} args - Arguments to update one SaleEventProduct.
   * @example
   * // Update one SaleEventProduct
   * const saleEventProduct = await prisma.saleEventProduct.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SaleEventProductUpdateArgs>(args: Prisma.SelectSubset<T, SaleEventProductUpdateArgs<ExtArgs>>): Prisma.Prisma__SaleEventProductClient<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SaleEventProducts.
   * @param {SaleEventProductDeleteManyArgs} args - Arguments to filter SaleEventProducts to delete.
   * @example
   * // Delete a few SaleEventProducts
   * const { count } = await prisma.saleEventProduct.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SaleEventProductDeleteManyArgs>(args?: Prisma.SelectSubset<T, SaleEventProductDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SaleEventProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventProductUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SaleEventProducts
   * const saleEventProduct = await prisma.saleEventProduct.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SaleEventProductUpdateManyArgs>(args: Prisma.SelectSubset<T, SaleEventProductUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SaleEventProducts and returns the data updated in the database.
   * @param {SaleEventProductUpdateManyAndReturnArgs} args - Arguments to update many SaleEventProducts.
   * @example
   * // Update many SaleEventProducts
   * const saleEventProduct = await prisma.saleEventProduct.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SaleEventProducts and only return the `id`
   * const saleEventProductWithIdOnly = await prisma.saleEventProduct.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SaleEventProductUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SaleEventProductUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SaleEventProduct.
   * @param {SaleEventProductUpsertArgs} args - Arguments to update or create a SaleEventProduct.
   * @example
   * // Update or create a SaleEventProduct
   * const saleEventProduct = await prisma.saleEventProduct.upsert({
   *   create: {
   *     // ... data to create a SaleEventProduct
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SaleEventProduct we want to update
   *   }
   * })
   */
  upsert<T extends SaleEventProductUpsertArgs>(args: Prisma.SelectSubset<T, SaleEventProductUpsertArgs<ExtArgs>>): Prisma.Prisma__SaleEventProductClient<runtime.Types.Result.GetResult<Prisma.$SaleEventProductPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SaleEventProducts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventProductCountArgs} args - Arguments to filter SaleEventProducts to count.
   * @example
   * // Count the number of SaleEventProducts
   * const count = await prisma.saleEventProduct.count({
   *   where: {
   *     // ... the filter for the SaleEventProducts we want to count
   *   }
   * })
  **/
  count<T extends SaleEventProductCountArgs>(
    args?: Prisma.Subset<T, SaleEventProductCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SaleEventProductCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SaleEventProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventProductAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SaleEventProductAggregateArgs>(args: Prisma.Subset<T, SaleEventProductAggregateArgs>): Prisma.PrismaPromise<GetSaleEventProductAggregateType<T>>

  /**
   * Group by SaleEventProduct.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventProductGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SaleEventProductGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SaleEventProductGroupByArgs['orderBy'] }
      : { orderBy?: SaleEventProductGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SaleEventProductGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSaleEventProductGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SaleEventProduct model
 */
readonly fields: SaleEventProductFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SaleEventProduct.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SaleEventProductClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  saleEvent<T extends Prisma.SaleEventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SaleEventDefaultArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SaleEventProduct model
 */
export interface SaleEventProductFieldRefs {
  readonly id: Prisma.FieldRef<"SaleEventProduct", 'String'>
  readonly amount: Prisma.FieldRef<"SaleEventProduct", 'Int'>
  readonly saleEventId: Prisma.FieldRef<"SaleEventProduct", 'String'>
  readonly productId: Prisma.FieldRef<"SaleEventProduct", 'String'>
}
    

// Custom InputTypes
/**
 * SaleEventProduct findUnique
 */
export type SaleEventProductFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * Filter, which SaleEventProduct to fetch.
   */
  where: Prisma.SaleEventProductWhereUniqueInput
}

/**
 * SaleEventProduct findUniqueOrThrow
 */
export type SaleEventProductFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * Filter, which SaleEventProduct to fetch.
   */
  where: Prisma.SaleEventProductWhereUniqueInput
}

/**
 * SaleEventProduct findFirst
 */
export type SaleEventProductFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * Filter, which SaleEventProduct to fetch.
   */
  where?: Prisma.SaleEventProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SaleEventProducts to fetch.
   */
  orderBy?: Prisma.SaleEventProductOrderByWithRelationInput | Prisma.SaleEventProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SaleEventProducts.
   */
  cursor?: Prisma.SaleEventProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SaleEventProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SaleEventProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SaleEventProducts.
   */
  distinct?: Prisma.SaleEventProductScalarFieldEnum | Prisma.SaleEventProductScalarFieldEnum[]
}

/**
 * SaleEventProduct findFirstOrThrow
 */
export type SaleEventProductFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * Filter, which SaleEventProduct to fetch.
   */
  where?: Prisma.SaleEventProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SaleEventProducts to fetch.
   */
  orderBy?: Prisma.SaleEventProductOrderByWithRelationInput | Prisma.SaleEventProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SaleEventProducts.
   */
  cursor?: Prisma.SaleEventProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SaleEventProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SaleEventProducts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SaleEventProducts.
   */
  distinct?: Prisma.SaleEventProductScalarFieldEnum | Prisma.SaleEventProductScalarFieldEnum[]
}

/**
 * SaleEventProduct findMany
 */
export type SaleEventProductFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * Filter, which SaleEventProducts to fetch.
   */
  where?: Prisma.SaleEventProductWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SaleEventProducts to fetch.
   */
  orderBy?: Prisma.SaleEventProductOrderByWithRelationInput | Prisma.SaleEventProductOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SaleEventProducts.
   */
  cursor?: Prisma.SaleEventProductWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SaleEventProducts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SaleEventProducts.
   */
  skip?: number
  distinct?: Prisma.SaleEventProductScalarFieldEnum | Prisma.SaleEventProductScalarFieldEnum[]
}

/**
 * SaleEventProduct create
 */
export type SaleEventProductCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * The data needed to create a SaleEventProduct.
   */
  data: Prisma.XOR<Prisma.SaleEventProductCreateInput, Prisma.SaleEventProductUncheckedCreateInput>
}

/**
 * SaleEventProduct createMany
 */
export type SaleEventProductCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SaleEventProducts.
   */
  data: Prisma.SaleEventProductCreateManyInput | Prisma.SaleEventProductCreateManyInput[]
}

/**
 * SaleEventProduct createManyAndReturn
 */
export type SaleEventProductCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * The data used to create many SaleEventProducts.
   */
  data: Prisma.SaleEventProductCreateManyInput | Prisma.SaleEventProductCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SaleEventProduct update
 */
export type SaleEventProductUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * The data needed to update a SaleEventProduct.
   */
  data: Prisma.XOR<Prisma.SaleEventProductUpdateInput, Prisma.SaleEventProductUncheckedUpdateInput>
  /**
   * Choose, which SaleEventProduct to update.
   */
  where: Prisma.SaleEventProductWhereUniqueInput
}

/**
 * SaleEventProduct updateMany
 */
export type SaleEventProductUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SaleEventProducts.
   */
  data: Prisma.XOR<Prisma.SaleEventProductUpdateManyMutationInput, Prisma.SaleEventProductUncheckedUpdateManyInput>
  /**
   * Filter which SaleEventProducts to update
   */
  where?: Prisma.SaleEventProductWhereInput
  /**
   * Limit how many SaleEventProducts to update.
   */
  limit?: number
}

/**
 * SaleEventProduct updateManyAndReturn
 */
export type SaleEventProductUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * The data used to update SaleEventProducts.
   */
  data: Prisma.XOR<Prisma.SaleEventProductUpdateManyMutationInput, Prisma.SaleEventProductUncheckedUpdateManyInput>
  /**
   * Filter which SaleEventProducts to update
   */
  where?: Prisma.SaleEventProductWhereInput
  /**
   * Limit how many SaleEventProducts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SaleEventProduct upsert
 */
export type SaleEventProductUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * The filter to search for the SaleEventProduct to update in case it exists.
   */
  where: Prisma.SaleEventProductWhereUniqueInput
  /**
   * In case the SaleEventProduct found by the `where` argument doesn't exist, create a new SaleEventProduct with this data.
   */
  create: Prisma.XOR<Prisma.SaleEventProductCreateInput, Prisma.SaleEventProductUncheckedCreateInput>
  /**
   * In case the SaleEventProduct was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SaleEventProductUpdateInput, Prisma.SaleEventProductUncheckedUpdateInput>
}

/**
 * SaleEventProduct delete
 */
export type SaleEventProductDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
  /**
   * Filter which SaleEventProduct to delete.
   */
  where: Prisma.SaleEventProductWhereUniqueInput
}

/**
 * SaleEventProduct deleteMany
 */
export type SaleEventProductDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SaleEventProducts to delete
   */
  where?: Prisma.SaleEventProductWhereInput
  /**
   * Limit how many SaleEventProducts to delete.
   */
  limit?: number
}

/**
 * SaleEventProduct without action
 */
export type SaleEventProductDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventProduct
   */
  select?: Prisma.SaleEventProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEventProduct
   */
  omit?: Prisma.SaleEventProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventProductInclude<ExtArgs> | null
}
