
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SaleEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SaleEvent
 * 
 */
export type SaleEventModel = runtime.Types.Result.DefaultSelection<Prisma.$SaleEventPayload>

export type AggregateSaleEvent = {
  _count: SaleEventCountAggregateOutputType | null
  _min: SaleEventMinAggregateOutputType | null
  _max: SaleEventMaxAggregateOutputType | null
}

export type SaleEventMinAggregateOutputType = {
  id: string | null
  to: string | null
  timestamp: Date | null
}

export type SaleEventMaxAggregateOutputType = {
  id: string | null
  to: string | null
  timestamp: Date | null
}

export type SaleEventCountAggregateOutputType = {
  id: number
  to: number
  timestamp: number
  _all: number
}


export type SaleEventMinAggregateInputType = {
  id?: true
  to?: true
  timestamp?: true
}

export type SaleEventMaxAggregateInputType = {
  id?: true
  to?: true
  timestamp?: true
}

export type SaleEventCountAggregateInputType = {
  id?: true
  to?: true
  timestamp?: true
  _all?: true
}

export type SaleEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SaleEvent to aggregate.
   */
  where?: Prisma.SaleEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SaleEvents to fetch.
   */
  orderBy?: Prisma.SaleEventOrderByWithRelationInput | Prisma.SaleEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SaleEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SaleEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SaleEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SaleEvents
  **/
  _count?: true | SaleEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SaleEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SaleEventMaxAggregateInputType
}

export type GetSaleEventAggregateType<T extends SaleEventAggregateArgs> = {
      [P in keyof T & keyof AggregateSaleEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSaleEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateSaleEvent[P]>
}




export type SaleEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SaleEventWhereInput
  orderBy?: Prisma.SaleEventOrderByWithAggregationInput | Prisma.SaleEventOrderByWithAggregationInput[]
  by: Prisma.SaleEventScalarFieldEnum[] | Prisma.SaleEventScalarFieldEnum
  having?: Prisma.SaleEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SaleEventCountAggregateInputType | true
  _min?: SaleEventMinAggregateInputType
  _max?: SaleEventMaxAggregateInputType
}

export type SaleEventGroupByOutputType = {
  id: string
  to: string
  timestamp: Date
  _count: SaleEventCountAggregateOutputType | null
  _min: SaleEventMinAggregateOutputType | null
  _max: SaleEventMaxAggregateOutputType | null
}

type GetSaleEventGroupByPayload<T extends SaleEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SaleEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SaleEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SaleEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SaleEventGroupByOutputType[P]>
      }
    >
  >



export type SaleEventWhereInput = {
  AND?: Prisma.SaleEventWhereInput | Prisma.SaleEventWhereInput[]
  OR?: Prisma.SaleEventWhereInput[]
  NOT?: Prisma.SaleEventWhereInput | Prisma.SaleEventWhereInput[]
  id?: Prisma.StringFilter<"SaleEvent"> | string
  to?: Prisma.StringFilter<"SaleEvent"> | string
  timestamp?: Prisma.DateTimeFilter<"SaleEvent"> | Date | string
  Products?: Prisma.ProductListRelationFilter
}

export type SaleEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  to?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  Products?: Prisma.ProductOrderByRelationAggregateInput
}

export type SaleEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SaleEventWhereInput | Prisma.SaleEventWhereInput[]
  OR?: Prisma.SaleEventWhereInput[]
  NOT?: Prisma.SaleEventWhereInput | Prisma.SaleEventWhereInput[]
  to?: Prisma.StringFilter<"SaleEvent"> | string
  timestamp?: Prisma.DateTimeFilter<"SaleEvent"> | Date | string
  Products?: Prisma.ProductListRelationFilter
}, "id">

export type SaleEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  to?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  _count?: Prisma.SaleEventCountOrderByAggregateInput
  _max?: Prisma.SaleEventMaxOrderByAggregateInput
  _min?: Prisma.SaleEventMinOrderByAggregateInput
}

export type SaleEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.SaleEventScalarWhereWithAggregatesInput | Prisma.SaleEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.SaleEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SaleEventScalarWhereWithAggregatesInput | Prisma.SaleEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SaleEvent"> | string
  to?: Prisma.StringWithAggregatesFilter<"SaleEvent"> | string
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"SaleEvent"> | Date | string
}

export type SaleEventCreateInput = {
  id?: string
  to: string
  timestamp?: Date | string
  Products?: Prisma.ProductCreateNestedManyWithoutSaleEventsInput
}

export type SaleEventUncheckedCreateInput = {
  id?: string
  to: string
  timestamp?: Date | string
  Products?: Prisma.ProductUncheckedCreateNestedManyWithoutSaleEventsInput
}

export type SaleEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Products?: Prisma.ProductUpdateManyWithoutSaleEventsNestedInput
}

export type SaleEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Products?: Prisma.ProductUncheckedUpdateManyWithoutSaleEventsNestedInput
}

export type SaleEventCreateManyInput = {
  id?: string
  to: string
  timestamp?: Date | string
}

export type SaleEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SaleEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SaleEventListRelationFilter = {
  every?: Prisma.SaleEventWhereInput
  some?: Prisma.SaleEventWhereInput
  none?: Prisma.SaleEventWhereInput
}

export type SaleEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SaleEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  to?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type SaleEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  to?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type SaleEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  to?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type SaleEventCreateNestedManyWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.SaleEventCreateWithoutProductsInput, Prisma.SaleEventUncheckedCreateWithoutProductsInput> | Prisma.SaleEventCreateWithoutProductsInput[] | Prisma.SaleEventUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.SaleEventCreateOrConnectWithoutProductsInput | Prisma.SaleEventCreateOrConnectWithoutProductsInput[]
  connect?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
}

export type SaleEventUncheckedCreateNestedManyWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.SaleEventCreateWithoutProductsInput, Prisma.SaleEventUncheckedCreateWithoutProductsInput> | Prisma.SaleEventCreateWithoutProductsInput[] | Prisma.SaleEventUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.SaleEventCreateOrConnectWithoutProductsInput | Prisma.SaleEventCreateOrConnectWithoutProductsInput[]
  connect?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
}

export type SaleEventUpdateManyWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.SaleEventCreateWithoutProductsInput, Prisma.SaleEventUncheckedCreateWithoutProductsInput> | Prisma.SaleEventCreateWithoutProductsInput[] | Prisma.SaleEventUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.SaleEventCreateOrConnectWithoutProductsInput | Prisma.SaleEventCreateOrConnectWithoutProductsInput[]
  upsert?: Prisma.SaleEventUpsertWithWhereUniqueWithoutProductsInput | Prisma.SaleEventUpsertWithWhereUniqueWithoutProductsInput[]
  set?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
  disconnect?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
  delete?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
  connect?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
  update?: Prisma.SaleEventUpdateWithWhereUniqueWithoutProductsInput | Prisma.SaleEventUpdateWithWhereUniqueWithoutProductsInput[]
  updateMany?: Prisma.SaleEventUpdateManyWithWhereWithoutProductsInput | Prisma.SaleEventUpdateManyWithWhereWithoutProductsInput[]
  deleteMany?: Prisma.SaleEventScalarWhereInput | Prisma.SaleEventScalarWhereInput[]
}

export type SaleEventUncheckedUpdateManyWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.SaleEventCreateWithoutProductsInput, Prisma.SaleEventUncheckedCreateWithoutProductsInput> | Prisma.SaleEventCreateWithoutProductsInput[] | Prisma.SaleEventUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.SaleEventCreateOrConnectWithoutProductsInput | Prisma.SaleEventCreateOrConnectWithoutProductsInput[]
  upsert?: Prisma.SaleEventUpsertWithWhereUniqueWithoutProductsInput | Prisma.SaleEventUpsertWithWhereUniqueWithoutProductsInput[]
  set?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
  disconnect?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
  delete?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
  connect?: Prisma.SaleEventWhereUniqueInput | Prisma.SaleEventWhereUniqueInput[]
  update?: Prisma.SaleEventUpdateWithWhereUniqueWithoutProductsInput | Prisma.SaleEventUpdateWithWhereUniqueWithoutProductsInput[]
  updateMany?: Prisma.SaleEventUpdateManyWithWhereWithoutProductsInput | Prisma.SaleEventUpdateManyWithWhereWithoutProductsInput[]
  deleteMany?: Prisma.SaleEventScalarWhereInput | Prisma.SaleEventScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type SaleEventCreateWithoutProductsInput = {
  id?: string
  to: string
  timestamp?: Date | string
}

export type SaleEventUncheckedCreateWithoutProductsInput = {
  id?: string
  to: string
  timestamp?: Date | string
}

export type SaleEventCreateOrConnectWithoutProductsInput = {
  where: Prisma.SaleEventWhereUniqueInput
  create: Prisma.XOR<Prisma.SaleEventCreateWithoutProductsInput, Prisma.SaleEventUncheckedCreateWithoutProductsInput>
}

export type SaleEventUpsertWithWhereUniqueWithoutProductsInput = {
  where: Prisma.SaleEventWhereUniqueInput
  update: Prisma.XOR<Prisma.SaleEventUpdateWithoutProductsInput, Prisma.SaleEventUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.SaleEventCreateWithoutProductsInput, Prisma.SaleEventUncheckedCreateWithoutProductsInput>
}

export type SaleEventUpdateWithWhereUniqueWithoutProductsInput = {
  where: Prisma.SaleEventWhereUniqueInput
  data: Prisma.XOR<Prisma.SaleEventUpdateWithoutProductsInput, Prisma.SaleEventUncheckedUpdateWithoutProductsInput>
}

export type SaleEventUpdateManyWithWhereWithoutProductsInput = {
  where: Prisma.SaleEventScalarWhereInput
  data: Prisma.XOR<Prisma.SaleEventUpdateManyMutationInput, Prisma.SaleEventUncheckedUpdateManyWithoutProductsInput>
}

export type SaleEventScalarWhereInput = {
  AND?: Prisma.SaleEventScalarWhereInput | Prisma.SaleEventScalarWhereInput[]
  OR?: Prisma.SaleEventScalarWhereInput[]
  NOT?: Prisma.SaleEventScalarWhereInput | Prisma.SaleEventScalarWhereInput[]
  id?: Prisma.StringFilter<"SaleEvent"> | string
  to?: Prisma.StringFilter<"SaleEvent"> | string
  timestamp?: Prisma.DateTimeFilter<"SaleEvent"> | Date | string
}

export type SaleEventUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SaleEventUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SaleEventUncheckedUpdateManyWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type SaleEventCountOutputType
 */

export type SaleEventCountOutputType = {
  Products: number
}

export type SaleEventCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Products?: boolean | SaleEventCountOutputTypeCountProductsArgs
}

/**
 * SaleEventCountOutputType without action
 */
export type SaleEventCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEventCountOutputType
   */
  select?: Prisma.SaleEventCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SaleEventCountOutputType without action
 */
export type SaleEventCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}


export type SaleEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  to?: boolean
  timestamp?: boolean
  Products?: boolean | Prisma.SaleEvent$ProductsArgs<ExtArgs>
  _count?: boolean | Prisma.SaleEventCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["saleEvent"]>

export type SaleEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  to?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["saleEvent"]>

export type SaleEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  to?: boolean
  timestamp?: boolean
}, ExtArgs["result"]["saleEvent"]>

export type SaleEventSelectScalar = {
  id?: boolean
  to?: boolean
  timestamp?: boolean
}

export type SaleEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "to" | "timestamp", ExtArgs["result"]["saleEvent"]>
export type SaleEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Products?: boolean | Prisma.SaleEvent$ProductsArgs<ExtArgs>
  _count?: boolean | Prisma.SaleEventCountOutputTypeDefaultArgs<ExtArgs>
}
export type SaleEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SaleEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SaleEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SaleEvent"
  objects: {
    Products: Prisma.$ProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    to: string
    timestamp: Date
  }, ExtArgs["result"]["saleEvent"]>
  composites: {}
}

export type SaleEventGetPayload<S extends boolean | null | undefined | SaleEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SaleEventPayload, S>

export type SaleEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SaleEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SaleEventCountAggregateInputType | true
  }

export interface SaleEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SaleEvent'], meta: { name: 'SaleEvent' } }
  /**
   * Find zero or one SaleEvent that matches the filter.
   * @param {SaleEventFindUniqueArgs} args - Arguments to find a SaleEvent
   * @example
   * // Get one SaleEvent
   * const saleEvent = await prisma.saleEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SaleEventFindUniqueArgs>(args: Prisma.SelectSubset<T, SaleEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SaleEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SaleEventFindUniqueOrThrowArgs} args - Arguments to find a SaleEvent
   * @example
   * // Get one SaleEvent
   * const saleEvent = await prisma.saleEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SaleEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SaleEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SaleEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventFindFirstArgs} args - Arguments to find a SaleEvent
   * @example
   * // Get one SaleEvent
   * const saleEvent = await prisma.saleEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SaleEventFindFirstArgs>(args?: Prisma.SelectSubset<T, SaleEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SaleEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventFindFirstOrThrowArgs} args - Arguments to find a SaleEvent
   * @example
   * // Get one SaleEvent
   * const saleEvent = await prisma.saleEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SaleEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SaleEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SaleEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SaleEvents
   * const saleEvents = await prisma.saleEvent.findMany()
   * 
   * // Get first 10 SaleEvents
   * const saleEvents = await prisma.saleEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const saleEventWithIdOnly = await prisma.saleEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SaleEventFindManyArgs>(args?: Prisma.SelectSubset<T, SaleEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SaleEvent.
   * @param {SaleEventCreateArgs} args - Arguments to create a SaleEvent.
   * @example
   * // Create one SaleEvent
   * const SaleEvent = await prisma.saleEvent.create({
   *   data: {
   *     // ... data to create a SaleEvent
   *   }
   * })
   * 
   */
  create<T extends SaleEventCreateArgs>(args: Prisma.SelectSubset<T, SaleEventCreateArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SaleEvents.
   * @param {SaleEventCreateManyArgs} args - Arguments to create many SaleEvents.
   * @example
   * // Create many SaleEvents
   * const saleEvent = await prisma.saleEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SaleEventCreateManyArgs>(args?: Prisma.SelectSubset<T, SaleEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SaleEvents and returns the data saved in the database.
   * @param {SaleEventCreateManyAndReturnArgs} args - Arguments to create many SaleEvents.
   * @example
   * // Create many SaleEvents
   * const saleEvent = await prisma.saleEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SaleEvents and only return the `id`
   * const saleEventWithIdOnly = await prisma.saleEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SaleEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SaleEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SaleEvent.
   * @param {SaleEventDeleteArgs} args - Arguments to delete one SaleEvent.
   * @example
   * // Delete one SaleEvent
   * const SaleEvent = await prisma.saleEvent.delete({
   *   where: {
   *     // ... filter to delete one SaleEvent
   *   }
   * })
   * 
   */
  delete<T extends SaleEventDeleteArgs>(args: Prisma.SelectSubset<T, SaleEventDeleteArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SaleEvent.
   * @param {SaleEventUpdateArgs} args - Arguments to update one SaleEvent.
   * @example
   * // Update one SaleEvent
   * const saleEvent = await prisma.saleEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SaleEventUpdateArgs>(args: Prisma.SelectSubset<T, SaleEventUpdateArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SaleEvents.
   * @param {SaleEventDeleteManyArgs} args - Arguments to filter SaleEvents to delete.
   * @example
   * // Delete a few SaleEvents
   * const { count } = await prisma.saleEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SaleEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, SaleEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SaleEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SaleEvents
   * const saleEvent = await prisma.saleEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SaleEventUpdateManyArgs>(args: Prisma.SelectSubset<T, SaleEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SaleEvents and returns the data updated in the database.
   * @param {SaleEventUpdateManyAndReturnArgs} args - Arguments to update many SaleEvents.
   * @example
   * // Update many SaleEvents
   * const saleEvent = await prisma.saleEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SaleEvents and only return the `id`
   * const saleEventWithIdOnly = await prisma.saleEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SaleEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SaleEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SaleEvent.
   * @param {SaleEventUpsertArgs} args - Arguments to update or create a SaleEvent.
   * @example
   * // Update or create a SaleEvent
   * const saleEvent = await prisma.saleEvent.upsert({
   *   create: {
   *     // ... data to create a SaleEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SaleEvent we want to update
   *   }
   * })
   */
  upsert<T extends SaleEventUpsertArgs>(args: Prisma.SelectSubset<T, SaleEventUpsertArgs<ExtArgs>>): Prisma.Prisma__SaleEventClient<runtime.Types.Result.GetResult<Prisma.$SaleEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SaleEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventCountArgs} args - Arguments to filter SaleEvents to count.
   * @example
   * // Count the number of SaleEvents
   * const count = await prisma.saleEvent.count({
   *   where: {
   *     // ... the filter for the SaleEvents we want to count
   *   }
   * })
  **/
  count<T extends SaleEventCountArgs>(
    args?: Prisma.Subset<T, SaleEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SaleEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SaleEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SaleEventAggregateArgs>(args: Prisma.Subset<T, SaleEventAggregateArgs>): Prisma.PrismaPromise<GetSaleEventAggregateType<T>>

  /**
   * Group by SaleEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SaleEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SaleEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SaleEventGroupByArgs['orderBy'] }
      : { orderBy?: SaleEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SaleEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSaleEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SaleEvent model
 */
readonly fields: SaleEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SaleEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SaleEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Products<T extends Prisma.SaleEvent$ProductsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SaleEvent$ProductsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SaleEvent model
 */
export interface SaleEventFieldRefs {
  readonly id: Prisma.FieldRef<"SaleEvent", 'String'>
  readonly to: Prisma.FieldRef<"SaleEvent", 'String'>
  readonly timestamp: Prisma.FieldRef<"SaleEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SaleEvent findUnique
 */
export type SaleEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * Filter, which SaleEvent to fetch.
   */
  where: Prisma.SaleEventWhereUniqueInput
}

/**
 * SaleEvent findUniqueOrThrow
 */
export type SaleEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * Filter, which SaleEvent to fetch.
   */
  where: Prisma.SaleEventWhereUniqueInput
}

/**
 * SaleEvent findFirst
 */
export type SaleEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * Filter, which SaleEvent to fetch.
   */
  where?: Prisma.SaleEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SaleEvents to fetch.
   */
  orderBy?: Prisma.SaleEventOrderByWithRelationInput | Prisma.SaleEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SaleEvents.
   */
  cursor?: Prisma.SaleEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SaleEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SaleEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SaleEvents.
   */
  distinct?: Prisma.SaleEventScalarFieldEnum | Prisma.SaleEventScalarFieldEnum[]
}

/**
 * SaleEvent findFirstOrThrow
 */
export type SaleEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * Filter, which SaleEvent to fetch.
   */
  where?: Prisma.SaleEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SaleEvents to fetch.
   */
  orderBy?: Prisma.SaleEventOrderByWithRelationInput | Prisma.SaleEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SaleEvents.
   */
  cursor?: Prisma.SaleEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SaleEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SaleEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SaleEvents.
   */
  distinct?: Prisma.SaleEventScalarFieldEnum | Prisma.SaleEventScalarFieldEnum[]
}

/**
 * SaleEvent findMany
 */
export type SaleEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * Filter, which SaleEvents to fetch.
   */
  where?: Prisma.SaleEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SaleEvents to fetch.
   */
  orderBy?: Prisma.SaleEventOrderByWithRelationInput | Prisma.SaleEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SaleEvents.
   */
  cursor?: Prisma.SaleEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SaleEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SaleEvents.
   */
  skip?: number
  distinct?: Prisma.SaleEventScalarFieldEnum | Prisma.SaleEventScalarFieldEnum[]
}

/**
 * SaleEvent create
 */
export type SaleEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * The data needed to create a SaleEvent.
   */
  data: Prisma.XOR<Prisma.SaleEventCreateInput, Prisma.SaleEventUncheckedCreateInput>
}

/**
 * SaleEvent createMany
 */
export type SaleEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SaleEvents.
   */
  data: Prisma.SaleEventCreateManyInput | Prisma.SaleEventCreateManyInput[]
}

/**
 * SaleEvent createManyAndReturn
 */
export type SaleEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * The data used to create many SaleEvents.
   */
  data: Prisma.SaleEventCreateManyInput | Prisma.SaleEventCreateManyInput[]
}

/**
 * SaleEvent update
 */
export type SaleEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * The data needed to update a SaleEvent.
   */
  data: Prisma.XOR<Prisma.SaleEventUpdateInput, Prisma.SaleEventUncheckedUpdateInput>
  /**
   * Choose, which SaleEvent to update.
   */
  where: Prisma.SaleEventWhereUniqueInput
}

/**
 * SaleEvent updateMany
 */
export type SaleEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SaleEvents.
   */
  data: Prisma.XOR<Prisma.SaleEventUpdateManyMutationInput, Prisma.SaleEventUncheckedUpdateManyInput>
  /**
   * Filter which SaleEvents to update
   */
  where?: Prisma.SaleEventWhereInput
  /**
   * Limit how many SaleEvents to update.
   */
  limit?: number
}

/**
 * SaleEvent updateManyAndReturn
 */
export type SaleEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * The data used to update SaleEvents.
   */
  data: Prisma.XOR<Prisma.SaleEventUpdateManyMutationInput, Prisma.SaleEventUncheckedUpdateManyInput>
  /**
   * Filter which SaleEvents to update
   */
  where?: Prisma.SaleEventWhereInput
  /**
   * Limit how many SaleEvents to update.
   */
  limit?: number
}

/**
 * SaleEvent upsert
 */
export type SaleEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * The filter to search for the SaleEvent to update in case it exists.
   */
  where: Prisma.SaleEventWhereUniqueInput
  /**
   * In case the SaleEvent found by the `where` argument doesn't exist, create a new SaleEvent with this data.
   */
  create: Prisma.XOR<Prisma.SaleEventCreateInput, Prisma.SaleEventUncheckedCreateInput>
  /**
   * In case the SaleEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SaleEventUpdateInput, Prisma.SaleEventUncheckedUpdateInput>
}

/**
 * SaleEvent delete
 */
export type SaleEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
  /**
   * Filter which SaleEvent to delete.
   */
  where: Prisma.SaleEventWhereUniqueInput
}

/**
 * SaleEvent deleteMany
 */
export type SaleEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SaleEvents to delete
   */
  where?: Prisma.SaleEventWhereInput
  /**
   * Limit how many SaleEvents to delete.
   */
  limit?: number
}

/**
 * SaleEvent.Products
 */
export type SaleEvent$ProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * SaleEvent without action
 */
export type SaleEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SaleEvent
   */
  select?: Prisma.SaleEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SaleEvent
   */
  omit?: Prisma.SaleEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleEventInclude<ExtArgs> | null
}
